### ISSUE TITLE
Add if a tool is available in a galaxy instance to the workflow

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy_tool_metadata_extractor#11]
It would be good to add weather a tool is available on a specific instance to this workflow, therefore the following script could be used and extended to query the tools from the 3 big instances 
https://github.com/bio-tools/biohackathon2022/blob/353570d03a3cccc73294b907c7c79ac9f814d815/scripts/workflowhub_galaxy_biotools.py#L24-L32
@supernord can the Australians take on this part ?

**Comment by paulzierep** [comment]
One thing to consider is, that the initial list we produce has a list of tool ids for each suite, so we would need to match each tool id and then decide what to show as output .... maybe tell the user each server that has at least one tool or the suite or all tools of a suite, but we cannot really give links to all tools, e.g. that would be 100 for mothur ...

**Comment by nsoranzo** [comment]
I can help with this as well, it should be easy to do in BioBlend if you are not against adding that as a Python requirement.

**Comment by paulzierep** [comment]
I think with bioblend should be fine. What are your thoughts about the way how to present it at the final list:
1) links for each tool to the instance (will be a bit much info in my opinion
2) a check [x] if at least one tool is in the instance
3) a check [x] if all tools are in the instance

Not sure if there is even a case where not all tools of a suite are installed

**Comment by supernord** [comment]
good question
there are examples of this - I don't think Galaxy Australia has all OpenMS tools installed
for the moment it depends on how comprehensive the list needs to be for it to be useful for the community - for some tools it may be important if not all tools are available

**Comment by supernord** [comment]
For reference, this is the script from BioHackathon 2022 for getting tools from an instance
https://github.com/bio-tools/biohackathon2022/blob/main/scripts/workflowhub_galaxy_biotools.py#L24-L49

**Comment by paulzierep** [comment]
Since we extract the bio.tools id directly from the wrapper, I don't think we need this part here.

**Comment by paulzierep** [comment]
> good question there are examples of this - I don't think Galaxy Australia has all OpenMS tools installed for the moment it depends on how comprehensive the list needs to be for it to be useful for the community - for some tools it may be important if not all tools are available

Maybe we could also present it like this e.g.:

Galaxy Shed Id: OpenMS 
Instance .eu (5/10)
Instance .org.au (7/10)
Instance .org (10/10)

**Comment by supernord** [comment]
> Since we extract the bio.tools id directly from the wrapper, I don't think we need this part here.

The key bit is the Galaxy API access, which is very straightforward.

**Comment by nsoranzo** [comment]
I'm looking into writing a function that given a list of tool IDs in the form `toolshed.g2.bx.psu.edu/repos/galaxyp/openms_falsediscoveryrate/FalseDiscoveryRate/2.6+galaxy0` and returning a pandas DataFrame (Galaxy servers x tool_ids) of True/False.
Let me know if this works!

**Comment by paulzierep** [comment]
@nsoranzo we do not really have a tool ID list in this way to start with, but only the wrapper id, but if we could produce the dataframe for all tools on the 3 main servers (~ 3-4.000 tools), we could just match the wrapper id to the tool id and that would work

**Comment by supernord** [comment]
Can we use the existing python function and update to extract the wrapper ids into a list?

<img width="782" alt="image" src="https://github.com/bebatut/galaxy_tool_extractor/assets/50811354/7385ce4e-09db-4490-ab5d-759c84143e8c">

**Comment by nsoranzo** [comment]
The proposed function is ready for review in https://github.com/bebatut/galaxy_tool_extractor/pull/23 .

**Comment by paulzierep** [comment]
Done: https://github.com/galaxyproject/galaxy_tool_metadata_extractor/pull/23
