### ISSUE TITLE
EDAM operation not extracted

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy_tool_metadata_extractor#3]
A quick look on https://docs.google.com/spreadsheets/d/1Nq_g-CPc8t_eC4M1NAS9XFJDflA7yE3b9hfSg3zu9L4/edit#gid=301051642 showed, that there are no EDAM operations present in the sheet. 
But, e.g. https://bio.tools/antismash does have EDAM operations annotated.

**Comment by supernord** [comment]
Are there EDAM annotations in the wrapper?
This might be because we aren't extracting metadata from bio.tools yet.
Only the bio.tools ID is being extracted from the tool wrapper.

**Comment by supernord** [comment]
This is how ToolFinder extracts bio.tools metadata: https://github.com/AustralianBioCommons/australianbiocommons.github.io/blob/master/finders/toolfinder.py#L198

**Comment by paulzierep** [comment]
The script does look in bio.tools directly: https://github.com/bebatut/galaxy_tool_extractor/blob/ce4b94cd4404f7751fb15101598c4a0bcacd4b8c/bin/extract_galaxy_tools.py#L261-L275 
And it works for the EDAM topic, but I need to check what the issue with the EDAM operation

**Comment by supernord** [comment]
It doesn't seem like there are any examples where it is working for operations.

**Comment by paulzierep** [comment]
I fixed it: https://github.com/bebatut/galaxy_tool_extractor/pull/4
