### ISSUE TITLE
Should we discuss the author's order?

### ISSUE THREAD

**Issue by supernord** [galaxyproject/galaxy_tool_metadata_extractor#86]
Should we discuss the author's order?

_Originally posted by @bebatut in https://github.com/galaxyproject/galaxy_tool_metadata_extractor/issues/79#issuecomment-2006756391_

Moving this to a new issue so that I can merge the PR and create a new preview pdf for the paper.

**Comment by supernord** [comment]
@bebatut @paulzierep

**Comment by bebatut** [comment]
Current order:
- Paul Zierep
- Bérénice Batut
- Nicola Soranzo
- Matúš Kalaš
- Ove Johan Ragnar Gustafsson
- Engy Nasr
- Tunc Kayikcioglu
- Joseph Wang

It feels more right that @supernord you are not lost in the middle. So either on the first or last position given the work you put in the preprint. Same for @matuskalas

**Comment by matuskalas** [comment]
I think you @bebatut @paulzierep @supernord absolutely should both discuss and decide this 😊

My suggestion would be that you 3 take the first-author and last-author places, just decide who of you which, gladly with "shared first" or "shared last" authorship. I'm fine with being somewhere in the middle.

Sure this isn't sooo crucial for a preprint, but it still might occassionally matter, and I'd also see it as an exercise for the next, "peer"-reviewed publication.

**Comment by matuskalas** [comment]
I reckon you @bebatut @paulzierep @supernord also know best how to order the contributors from Freiburg and Australia.

@supernord, was it really only Joseph & you contributing from AU?? I had a feeling you were a big group 😮

**Comment by matuskalas** [comment]
> I think you @bebatut @paulzierep @supernord absolutely should both discuss and decide this 😊

But yeah, if you don't have time to discuss or cannot/hesitate to decide, I can give you as apparently the most senior co-author a suggestion 😉😋

**Comment by supernord** [comment]
I'm happy to be last author.

> @supernord, was it really only Joseph & you contributing from AU?? I had a feeling you were a big group 😮
I don't think we have overlooked anyone. We were a big group, but we were also working across a few projects at once. 
I'm checking again now, just to be sure.

**Comment by supernord** [comment]
https://github.com/galaxyproject/galaxy_tool_metadata_extractor/pull/87

**Comment by bebatut** [comment]
What about then @paulzierep and me as first authors, @supernord as last, and everyone in the middle in alphabetical order?

**Comment by paulzierep** [comment]
> What about then @paulzierep and me as first authors, @supernord as last, and everyone in the middle in alphabetical order?

Sorry for being late here, I agree on that !
