### ISSUE TITLE
Please help with DOI

### ISSUE THREAD

**Issue by matuskalas** [galaxyproject/galaxy_tool_metadata_extractor#96]
Hi @paulzierep @bebatut @supernord, urgent help please 😊

How long did it take for you to get the DOI after you submitted the preprint? And how did you get it?

CC @beatrizserrano @rioualen

Billion thanks!!! 🙏🏽🙏🏽🙇🏽‍♂️

**Comment by rioualen** [comment]
I'm just about to submit it now, please let me know if you have any news!

**Comment by rioualen** [comment]
I just got the approval and DOI! That was fast!

**Comment by matuskalas** [comment]
Thank you all 🙏🏽

I the end no need for panic 😅
